version: '3'

services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - common-net
    env_file:
      - stack.env
    expose:
      - 8080

volumes:
  evolution_instances:

networks:
  common-net:
    name: common-net
    driver: bridge
